name: BuildAndPackageAzureMonitorLogger

on:
  push:
    branches:
      - main
    paths:
      - 'AICentral/**'
  pull_request:
    branches:
      - main
    paths:
      - 'AICentral.Logging.AzureMonitor/**'
  workflow_dispatch:

jobs:
  build-and-package-app:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.10'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Test
        run: dotnet test AICentralTests/AICentralTests.csproj

      - name: Pack Nuget
        run: dotnet pack AICentral.Logging.AzureMonitor/AICentral.Logging.AzureMonitor.csproj -p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }} --output ./publish/
      
      - name: Publish to Nuget ${{ steps.gitversion.outputs.NuGetVersionV2 }}
        run: dotnet nuget push ./publish/AICentral.Logging.AzureMonitor.${{ steps.gitversion.outputs.NuGetVersionV2 }}.nupkg  --api-key ${{ secrets.NUGET_PUBLISH_KEY }} --source https://api.nuget.org/v3/index.json
