name: PublishDocker

on:
  workflow_dispatch:

jobs:
  build-and-publish-docker-container:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions: 
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ needs.build-and-package-app.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: NUGET_VERSION=${{ steps.gitversion.outputs.NuGetVersionV2 }}
          tags: |
            ghcr.io/graemefoster/aicentral:latest
            ghcr.io/graemefoster/aicentral:${{ steps.gitversion.outputs.NuGetVersionV2 }}
